### ISSUE TITLE
Disclaimer en Filtros de Búsqueda - 

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/portal-de-datos#100]
Adjunto mockup para el despliegue del disclaimer en filtros de búsqueda: 
El texto es el siguiente: 
"Esta no es una búsqueda por coordenadas, los resultados se corresponden con el campo “Departamento” del estándar DwC documentado por el publicador."
![filtros-tooltip](https://user-images.githubusercontent.com/14220404/35169795-e7722a5a-fd2b-11e7-8b1f-eb110861a425.png)

**Comment by camiplata** [comment]
El issue fue solucionado parcialmente, funciona en el portar de datos pero falta implementarlo en los canales de colecciones y listas.

**Comment by iraida07** [comment]
Migrado a listas, se cierra en Portal de datos

**Comment by camiplata** [comment]
@iraida07 también quedó migrado a colecciones?

**Comment by iraida07** [comment]
Sí ya está copiado tambien
