### ISSUE TITLE
RECURSO | BÚSQUEDA | Paginación en la búsqueda por recurso

### ISSUE THREAD

**Issue by RicardoOrtizG** [SIB-Colombia/portal-de-datos#169]
La paginación en la búsqueda por recursos no funciona, el número de la pagina cambia pero me muestra los mismo 10 recursos.

![image](https://user-images.githubusercontent.com/15789737/42327472-5f490c00-8031-11e8-94b8-45cec8c5aaa7.png)

**Comment by iraida07** [comment]
Se implementó funcionalidad para desplegar recursos en forma de lista.
