### ISSUE TITLE
REGISTROS | BÚSQUEDA POR REGISTROS | RECURSOS | Paginación no funcional en búsqueda por recursos

### ISSUE THREAD

**Issue by RicardoOrtizG** [SIB-Colombia/portal-de-datos#185]
La paginación en la búsqueda por recursos no está funcionando, muestra siempre los mismos 10 resultados, aunque se cambie la página

![image](https://user-images.githubusercontent.com/15789737/42390094-701493b2-8110-11e8-88be-b25a39b8e018.png)

**Comment by dapino** [comment]
Se solucionó con un botón de "cargar más", aún hay inconsistencias que se relacionan en el issue #254
