### ISSUE TITLE
PAGINACIÓN

### ISSUE THREAD

**Issue by dapino** [SIB-Colombia/portal-de-datos#196]
La paginación en portal, listas y colecciones, debe:
-Cargar contenido de la página a la que se está haciendo clic
-Agregar a la url la página que está activa
-Marcar en el paginador el número de página activa
-Presentar solo el número de páginas disponibles
-No mostrarse si los elementos que hay disponibles no exceden la cantidad máxima de una página

**Comment by dapino** [comment]
- [ ] hola

**Comment by iraida07** [comment]
Se cierra este issue porque no vamos a manejar Epics hasta que se solucione Issue con este componente de Zenhub. https://github.com/ZenHubIO/support/issues/1582#issuecomment-443029056
