### ISSUE TITLE
FILTROS

### ISSUE THREAD

**Issue by dapino** [SIB-Colombia/portal-de-datos#197]
Los filtros presentan los siguientes problemas:
-Cuando se ingresa a la búsqueda desde un filtro por grupo biológico desde el home, debería activarse el filtro correspondiente.
-Cuando se ingresa a la búsqueda por una url con múltiples parámetros, deberían estar activos los filtros correspondientes.
-Cuando se ingresa por los filtros de búsqueda ubicados en el header. deberían activarse los filtros correspondientes con la búsqueda seleccionada.
-Cuando se realiza la búsqueda

**Comment by iraida07** [comment]
Se cierra este issue porque no vamos a manejar Epics hasta que se solucione Issue con este componente de Zenhub. https://github.com/ZenHubIO/support/issues/1582#issuecomment-443029056

**Antencion:** ¡Esto no queire decir que se cierran los issues relacionados con este modulo!
