### ISSUE TITLE
FILTRO SUPERIOR | Error de contenido en el nombre de la licencia Public Domain

### ISSUE THREAD

**Issue by RicardoOrtizG** [SIB-Colombia/portal-de-datos#251]
La licencia Public Domain o CC 0, aparece en las opciones de filtro como CC 1.0

![image](https://user-images.githubusercontent.com/15789737/49102871-eb5adb00-f247-11e8-80e5-b0b93353aa1d.png)

La forma correcta debe ser CC0 1.0 acorde con este link a la licencia
https://creativecommons.org/publicdomain/zero/1.0/deed.es

**Comment by iraidamercedes** [comment]
migrado a gitlab
