### ISSUE TITLE
En categoría taxonómica, aparece un filtro en blanco.

### ISSUE THREAD

**Issue by iraida07** [SIB-Colombia/portal-de-datos#252]
Al desplegar filtros de categoría taxonómica, hay un filtro en blanco. Por favor  @leobuitrago  definir que nombre colocar ahí para indicarle a lumon que cuando encuentre ese vacío, ese campo aparezca con ese nombre.

![image.png](https://images.zenhubusercontent.com/5bd9c6818342b456dad107ae/cb50bbff-8e87-4b38-8323-95f7fd501b37)

**Comment by iraidamercedes** [comment]
mira a gitlab.
