### ISSUE TITLE
REGISTROS | BÚSQUEDA POR REGISTROS | RECURSOS | No muestra el total de recursos

### ISSUE THREAD

**Issue by dapino** [SIB-Colombia/portal-de-datos#254]
El botón debe decir cuanto recursos de cuantos en total se están mostrando actualmente
![captura de pantalla 2018-12-19 a la s 9 35 35 a m](https://user-images.githubusercontent.com/11689269/50226643-bedf3e00-0371-11e9-8ffa-d8b1e6146b0b.png)

Y debe decir el número total de recursos, no registros
![captura de pantalla 2018-12-19 a la s 9 35 48 a m](https://user-images.githubusercontent.com/11689269/50226644-bedf3e00-0371-11e9-809c-de6b24eecd48.png)

**Comment by iraida07** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CONSULTA | Desarrollar lógica para mostrar el total de recursos en portal de datos.](https://trello.com/c/ycwyvBtx/107-consulta-desarrollar-l%C3%B3gica-para-mostrar-el-total-de-recursos-en-portal-de-datos)
