### ISSUE TITLE
BÚSQUEDA POR REGISTROS | paginación en búsqueda por 'REGISTROS'  | al pasar de página limpia los filtros

### ISSUE THREAD

**Issue by dapino** [SIB-Colombia/portal-de-datos#255]
![ezgif-2-1e1014aa2a97.gif](https://images.zenhubusercontent.com/5b0ed04054b51e4165e1d59d/9862df75-9989-4b07-ba9e-5ef216fae2d8)

**Comment by jag2kn** [comment]
El contexto de la búsqueda actual cuando se cambia de página se pierde.

Este issue debe pasar a filtros no paginación

**Comment by iraidamercedes** [comment]
migrado a gitlab
