### ISSUE TITLE
Descarga del Portal arroja error 404

### ISSUE THREAD

**Issue by RicardoOrtizG** [SIB-Colombia/portal-de-datos#257]
Al intentar hacer una descarga sobre un filtro en el Portal de datos, pide registrarse, luego del login aparece la siguiente ventana emergente.

![image](https://user-images.githubusercontent.com/15789737/50920872-82ed4500-1414-11e9-9501-b22620d0a4fb.png)

Efectivamente al correo registrado llega un link para la descarga

![image](https://user-images.githubusercontent.com/15789737/50920922-b0d28980-1414-11e9-837e-471e8bf94700.png)

Al dar clic al link, aparece la siguiente página de error

![image](https://user-images.githubusercontent.com/15789737/50920985-e11a2800-1414-11e9-9f3f-f794d7067774.png)

**Comment by iraida07** [comment]
Para poder descargar se debe cambiar **apies.biodiversidad.co** en url por **192.168.11.39:8001**

http://apies.biodiversidad.co/api/download/5fd5310083ce5553da63f269d04ff481d695a5e5.zip

http://192.168.11.39:8001/api/download/5fd5310083ce5553da63f269d04ff481d695a5e5.zip


Haciendo esto, la descarga del .zip se realiza automáticamente.

**Comment by jag2kn** [comment]
Esto es en el servidor de pruebas, en producción el link está correcto
