### ISSUE TITLE
Búsqueda por occurrenceID no muestra todos los resultados si el occurrenceID no es único

### ISSUE THREAD

**Issue by RicardoOrtizG** [SIB-Colombia/portal-de-datos#261]
La búsqueda de un registro por URL está anidada al occurrenceID, sin embargo, los occurrenceID son generados manualmente, por lo que no hay garantía de que no se repitan.

Al explorar los datos de Colombia en GBIF (Sin repatriados), hay 19.605 registros con occurrenceID duplicado. 

Ejemplo: 
occurrenceID = FM:FM:0001

El cual corresponde a los siguientes registros en GBIF:
[Acanthurus nigricans (Linnaeus, 1758)](https://www.gbif.org/occurrence/1314759185)
[Pocillopora capitata Verrill, 1864](https://www.gbif.org/occurrence/1314770576)
[Pterodroma phaeopygia (Salvin, 1876)](https://www.gbif.org/occurrence/1315953442)
[Alpheus grahami Abele, 1975](https://www.gbif.org/occurrence/1315954309)

En el Portal de datos solo se muestra la última opción, aunque los demás datos estén indexados.

http://datos.biodiversidad.co/occurrence/FM:FM:0001, 

Cómo se ve en el siguiente enlace la segunda opción de registro, si está en el portal, pero abre el mismo registro de Alpheus grahami Abele, 1975.

http://datos.biodiversidad.co/search?scientificName=Pocillopora%20capitata%20Verrill,%201864&organizationId=ef3ec46c-c2e6-4674-a663-77b334fa6003

**Comment by iraidamercedes** [comment]
migrado a gitlab
