### ISSUE TITLE
Archivo de descarga del Portal con elementos desorganizados, no necesarios y faltantes

### ISSUE THREAD

**Issue by RicardoOrtizG** [SIB-Colombia/portal-de-datos#262]
En las pruebas a la descarga desde el Portal se encontró que hay elementos que no es necesario incluir, pues hacen parte del funcionamiento interno del indexador o son parte de los metadatos y generan errores como saltos de línea, ya que  son campos abiertos (Ejemplo: abstract)

A continuación se adjunta un documento (spreadsheet). En la hoja 'Descargas', se encuentra una clasificación de los elementos que no van en la descarga y el orden sugerido para las columnas en el archivo.

De igual forma se listan algunos elementos que por su importancia deberían incluirse en la descarga

[Documento Indeexación Cronograma y Conteos | Descargas](https://docs.google.com/spreadsheets/d/1yF238NNHh8hDmnGt_F5_QsdPcZ7MOKN3eLlOZTKI_U4/edit?ts=5c3fc064#gid=1373470946)

**Comment by iraida07** [comment]
Lista de columnas que debería traer el csv: 

organizationName
doi
titleResource
occurrenceID
basisOfRecord
institutionCode
collectionCode
catalogNumber
type
language
license
rightsHolder
institutionID
collectionID
datasetName
occurrenceRemarks
recordNumber
recordedBy
organismQuantity
organismQuantityType
sex
lifeStage
preparations
disposition
previousIdentifications
samplingProtocol
year
month
day
fieldNumber
fieldNotes
continent
country
countryCode
stateProvince
county
locality
verbatimLocality
verbatimElevation
minimumElevationInMeters
maximumElevationInMeters
minimumDepthInMeters
maximumDepthInMeters
decimalLatitude
decimalLongitude
geodeticDatum
identifiedBy
identificationRemarks
typeStatus
dateIdentified
scientificName
kingdom
phylum
class
order
family
genus
specificEpithet
infraSpecificEpithet
taxonRank
verbatimTaxonRank
scientificNameAuthorship
vernacularName
taxonomicStatus

**Comment by iraidamercedes** [comment]
Se implementó el ajuste el año pasado en el cópdigo de descargas
