### ISSUE TITLE
Tiempo de espera de notificación muy largo para descargas pesadas

### ISSUE THREAD

**Issue by RicardoOrtizG** [SIB-Colombia/portal-de-datos#263]
Durante las pruebas, al descargar un dataset grande (ejemplo: Invertebrados del IAvH; 131409 registros), no aparece ningún mensaje, pareciera que no hubiera funcionado, luego de 15 o 20 minutos aparece la ventana emergente notificando que la descarga llegará al correo. 

Creo que aúnque la descarga se demore la notificación debe ser inmediata, para no dar la sensación de que no funciona, ya que parece sincronizada con la llegada del correo con el resultado de la descarga.

[Link descarga ejemplo:](http://192.168.11.119:3000/search?phylum=Acanthocephala&phylum=annelida&phylum=arthropoda&phylum=brachiopoda&phylum=bryozoa&phylum=chaetognatha&phylum=cnidaria&phylum=echinodermata&phylum=gastrotricha&phylum=mollusca&phylum=myxozoa&phylum=nematoda&phylum=onychophora&phylum=platyhelminthes&phylum=porifera&phylum=rotifera&phylum=sipuncula)

**Comment by iraidamercedes** [comment]
migrado a gitlab
