### ISSUE TITLE
Contenido del correo de descarga

### ISSUE THREAD

**Issue by RicardoOrtizG** [SIB-Colombia/portal-de-datos#264]
El cuerpo del correo de la descarga puede tener el siguiente contenido:

Hola [nombre de usuario]

Los datos consultados en el Portal de Datos del SiB Colombia están disponibles para descarga en la siguiente dirección: 

[http://apies.biodiversidad.co/api/download/0bfe79024873fa6aae4a5ed52dbe81fa857529ea.zip]

Detalles del archivo:

Fecha de generación: [miércoles, 2 de mayo de 2018 8:53] 
No. de registros biológicos: [184993]
Tamaño de archivo: [10.44] MB 

**Nota:** El archivo descargado se encuentra en formato **.csv** (valores separados por comas)  y codificación **UTF8**, tenga esta información presente si desea importar los datos con excel a través de la opción Importar archivos de texto.

Gracias por usar nuestro sistema de información.

Cordialmente,

(firma del correo SiB Colombia)

@javiesgm, @leobuitrago de acuerdo?

**Comment by RicardoOrtizG** [comment]
Notificación actual:

![image](https://user-images.githubusercontent.com/15789737/51502759-7dddad80-1da5-11e9-81ed-f7a472fb8b69.png)

**Comment by RicardoOrtizG** [comment]
@javiesgm  @leobuitrago . Estaba pensando que aunque se podría añadir un anexo en la descarga con la información de citación y derechos de uso (licencia), eso genera mas peso en el archivo y por ende consume mas espacio en el servidor. Creo que es mejor si aprovechamos el correo para indicar como obtener la información de citación y licencia.  Esta es mi propuesta.

"Los datos compartidos a través del SiB Colombia son aportados por diferentes entidades nacionales e internacionales y se encuentran bajo el uso de licencias Creative Commons (ver **license** en la descarga). Recomendamos dar la atribución correspondiente a las organizaciones publicadoras frente al uso que se vaya a hacer de esta información." 

"A través del elemento **doi** en la descarga, puede acceder a la publicación y encontrar los detalles de citación de los datos".

Quedo atento a sus recomendaciones!

**Comment by javiesgm** [comment]
Gracias Richie!

Va con ajustes: 

Asunto [Descarga - SiB Colombia]
¡Hola [nombre de usuario]!
Para descargar los datos consultados en el Portal de Datos del SiB Colombia, **haz clic **AQUÍ****

_**Nota:** El archivo descargado se encuentra en formato .csv (valores separados por comas) y codificación UTF8, te presente esta información si vas a importar los datos con excel a través de la opción Importar archivos de texto._

**Uso y atribución:** 
Los datos que se comparten a través del SiB Colombia provienen de diferentes entidades nacionales e internacionales que aportan al conocimiento abierto. En el SiB Colombia los llamamos socios publicadores. Las condiciones de uso de esta información las define cada socio publicador mediante licencias Creative Commons. Por eso es necesario leer y respetar las condiciones legales que aparecen asociadas a cada uno de los contenidos. Para consultarlas puedes ver el elemento _**’license’**_ en la descarga o puedes encontrar los detalles de citación siguiendo el elemento _**‘doi’.**_ 

	•	Siempre que utilices los datos o la información disponible a través de los canales de participación del SiB Colombia, debes dar el crédito a quien corresponda. Si son varias fuentes, debes citarlas a todas. 
	•	No suprimas la información del autor que el publicador haya asociado a los datos o a la información. 
	•	Reconoce que los datos y la información son suministrados con buena fe respecto de su calidad, validez y relevancia en el momento de su publicación, por eso al utilizarlos lo haces bajo tu propia responsabilidad. 
	•	Ser cuidadoso en la citación es la forma de reconocer y agradecer el trabajo de los demás, por eso es tan importante. 

Para más información sobre la política de acceso abierto del SiB Colombia, consulta: [https://www.sibcolombia.net/acceso-abierto]

Gracias por utilizar nuestros canales de participación. 

Cordialmente, 

Equipo coordinador del SiB Colombia

@iraida07 @dapino por favor revisar con @jag2kn 

@daiesco, ¿cómo lo ves? esto iría desde el correo sib@humboldt.org.co? o ¿generamos uno nuevo? descargas@biodiversidad.co ¿?

**Comment by daiesco** [comment]
Va con ajustes aprovechando lo que me preguntan:

Asunto [Descarga - SiB Colombia]
¡Hola [nombre de usuario]!
Muchas gracias por hacer uso de los canales de participación del SiB Colombia. Para descargar los datos consultados en el Portal de Datos, haz clic AQUÍ o en el siguiente enlace:

[enlace]

_**Nota**: El archivo descargado se encuentra en formato .csv (valores separados por comas) y codificación UTF8, ten presente esta información si vas a visualizar el archivo con un procesador de texto. En el caso de Excel usa la opción Importar archivos de texto._

**Uso y atribución:**
Los datos que se comparten a través del SiB Colombia provienen de diferentes entidades nacionales e internacionales que aportan al conocimiento abierto. En el SiB Colombia los llamamos socios publicadores. Las condiciones de uso de esta información las define cada socio publicador mediante licencias Creative Commons. Por eso es necesario leer y respetar las condiciones legales que aparecen asociadas a cada uno de los contenidos. Para consultarlas puedes ver el elemento **_’license’_** en la descarga o puedes encontrar los detalles de citación siguiendo el elemento **_‘doi’_**.

•	Siempre que utilices los datos o la información disponible a través de los canales de participación del SiB Colombia, debes dar el crédito a quien corresponda. Si son varias fuentes, debes citarlas a todas. 
•	No suprimas la información del autor que el publicador haya asociado a los datos o a la información. _[Esto no lo entiendo...]_
•	Reconoce que los datos y la información son suministrados con buena fe respecto de su calidad, validez y relevancia en el momento de su publicación, por eso al utilizarlos lo haces bajo tu propia responsabilidad. 
•	Ser cuidadoso en la citación es la forma de reconocer y agradecer el trabajo de los demás, por eso es tan importante. 
Para más información sobre la política de acceso abierto del SiB Colombia, consulta: [https://www.sibcolombia.net/acceso-abierto]

Gracias por utilizar nuestros canales de participación.

Cordialmente,

**Equipo Coordinador del SiB Colombia**

_Por favor no responda a este mensaje. Este mensaje se envió desde una cuenta de correo automática por una solicitud de descarga._

Frente al correo de envío que sea descargas@sibcolombia.net

**Comment by jag2kn** [comment]
La cuenta desde donde se envía el correo se configura en:

https://gitlab.com/sib-colombia/portal-de-datos-backend/blob/master/flask/download.py#L14

**Comment by iraida07** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [DESCARGAS | Ajustar mensaje de descargas en portal de datos.](https://trello.com/c/cQsfOncA/116-descargas-ajustar-mensaje-de-descargas-en-portal-de-datos)

**Comment by iraidamercedes** [comment]
Se cierra y se cierra en gitlab en : https://gitlab.com/sib-colombia/portal-de-datos-backend/issues/1
