### ISSUE TITLE
Valores de fecha en la descarga mapeados con valores extraños

### ISSUE THREAD

**Issue by RicardoOrtizG** [SIB-Colombia/portal-de-datos#265]
En el archivo descargado las fechas tienen valores de -1, -2, 0 para eventDate_year,  eventDate_month y  eventDate_day. Y no esta la fecha concatenada eventDate.

Ejemplo descarga.
[a0759579ba56073d2b399c4ab433eb73af50b50c.txt](https://github.com/SIB-Colombia/portal-de-datos/files/2853380/a0759579ba56073d2b399c4ab433eb73af50b50c.txt)

**Comment by iraidamercedes** [comment]
migrado a gitlab
