### ISSUE TITLE
Explorador geográfico - Capas faltantes

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/portal-de-datos#84]
@leobuitrago: 

* Contorno de Colombia

**Comment by johnfra797** [comment]
Cual seria el geojson?

**Comment by iraida07** [comment]
@leobuitrago @jag2kn  por favor explicar este issue y verificar si está resuelto, no se entiende bien.

**Comment by RicardoOrtizG** [comment]
@iraida07 . Este Issue lo puedes cerrar, es muy viejo, El issue #120  se respondió aclarando ese tema
